{
 "title": "New dashboard",
 "time": { "from": "2022-08-31T17:00:00.000Z", "to": "2022-09-06T17:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "wo", "query": "SELECT no_wo FROM test" }
  ]
 },
 "panels": [
  {
   "title": "C23 (Electric Motor-Cooling Fan)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT tgl, nli1 AS 'No Load i1', nli2 AS 'No Load i2', nli3 AS 'No Load i3',\r\nloi1 AS 'Loaded i1', loi2 AS 'Loaded i2', loi3 AS 'Loaded i3' FROM test\r\nWHERE no_wo = $wo AND\r\nid_equip = 'C23' AND\r\nid_tipeq = 'EMF'"
    }
   ]
  },
  {
   "title": "C23 (Electric Motor-Drive)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT tgl, nli1 AS 'No Load i1', nli2 AS 'No Load i2', nli3 AS 'No Load i3',\r\nloi1 AS 'Loaded i1', loi2 AS 'Loaded i2', loi3 AS 'Loaded i3' FROM test\r\nWHERE no_wo = $wo AND\r\nid_equip = 'C23' AND\r\nid_tipeq = 'EMD'"
    }
   ]
  },
  {
   "title": "C22 (Electric-Motor Fan)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT tgl, nli1 AS 'No Load i1', nli2 AS 'No Load i2', nli3 AS 'No Load i3',\r\nloi1 AS 'Loaded i1', loi2 AS 'Loaded i2', loi3 AS 'Loaded i3' FROM test\r\nWHERE no_wo = $wo AND\r\nid_equip = 'C22' AND\r\nid_tipeq = 'EMF'"
    }
   ]
  },
  {
   "title": "C22 (Electric Motor)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT tgl, nli1 AS 'No Load i1', nli2 AS 'No Load i2', nli3 AS 'No Load i3',\r\nloi1 AS 'Loaded i1', loi2 AS 'Loaded i2', loi3 AS 'Loaded i3' FROM test\r\nWHERE no_wo = $wo AND\r\nid_equip = 'C22' AND\r\nid_tipeq = 'EMD'"
    }
   ]
  },
  {
   "title": "RF 22 (Electric Motor-Fan)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT tgl, nli1 AS 'No Load i1', nli2 AS 'No Load i2', nli3 AS 'No Load i3',\r\nloi1 AS 'Loaded i1', loi2 AS 'Loaded i2', loi3 AS 'Loaded i3' FROM test\r\nWHERE no_wo = $wo AND\r\nid_equip = 'RF22' AND\r\nid_tipeq = 'EMF'"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "RF 22 (Electric Motor Drive)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT tgl, nli1 AS 'No Load i1', nli2 AS 'No Load i2', nli3 AS 'No Load i3',\r\nloi1 AS 'Loaded i1', loi2 AS 'Loaded i2', loi3 AS 'Loaded i3' FROM test\r\nWHERE no_wo = $wo AND\r\nid_equip = 'RF22' AND\r\nid_tipeq = 'EMD'"
    }
   ]
  },
  {
   "title": "Sentiment",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT d.sentiment, count(d.sentiment) FROM (\r\nSELECT\r\n(\r\nCASE\r\nWHEN polarity = 0 THEN 2\r\nWHEN polarity < 0 THEN 3\r\nELSE 1\r\nEND\r\n) pos,\r\n(\r\nCASE\r\nWHEN polarity = 0 THEN 'Neutral'\r\nWHEN polarity < 0 THEN 'Negative'\r\nELSE 'Positive'\r\nEND\r\n) sentiment\r\nFROM tweets\r\nWHERE polarity IS NOT NULL AND id_target=1\r\nAND tweet_created::DATE BETWEEN '2022-09-01' AND '2022-09-20'\r\n) d\r\nGROUP BY d.pos, d.sentiment\r\nORDER BY pos ASC"
    }
   ]
  }
 ]
}